ALTER SESSION SET CURRENT_SCHEMA=app_user;

CREATE TABLE CLIENTES (
  ID NUMBER PRIMARY KEY,
  NOMBRE VARCHAR2(120) NOT NULL,
  EMAIL VARCHAR2(180),
  IDENTIFICACION VARCHAR2(40) UNIQUE,
  CREATED_AT TIMESTAMP,
  UPDATED_AT TIMESTAMP
);
CREATE SEQUENCE CLIENTES_SEQ START WITH 1;
CREATE OR REPLACE TRIGGER CLIENTES_BI
BEFORE INSERT ON CLIENTES FOR EACH ROW
BEGIN
  IF :NEW.ID IS NULL THEN SELECT CLIENTES_SEQ.NEXTVAL INTO :NEW.ID FROM DUAL; END IF;
  :NEW.CREATED_AT := SYSTIMESTAMP; :NEW.UPDATED_AT := SYSTIMESTAMP;
END;
/

CREATE TABLE FACTURAS (
  ID NUMBER PRIMARY KEY,
  CLIENTE_ID NUMBER NOT NULL,
  MONTO NUMBER(12,2) NOT NULL,
  FECHA DATE NOT NULL,
  DESCRIPCION VARCHAR2(400),
  CREATED_AT TIMESTAMP,
  UPDATED_AT TIMESTAMP,
  CONSTRAINT FK_FACTURAS_CLIENTE FOREIGN KEY (CLIENTE_ID) REFERENCES CLIENTES(ID)
);
CREATE SEQUENCE FACTURAS_SEQ START WITH 1;
CREATE OR REPLACE TRIGGER FACTURAS_BI
BEFORE INSERT ON FACTURAS FOR EACH ROW
BEGIN
  IF :NEW.ID IS NULL THEN SELECT FACTURAS_SEQ.NEXTVAL INTO :NEW.ID FROM DUAL; END IF;
  :NEW.CREATED_AT := SYSTIMESTAMP; :NEW.UPDATED_AT := SYSTIMESTAMP;
END;
/
