class Cliente < ApplicationRecord
  self.table_name  = "CLIENTES"
  self.primary_key = "ID"
  self.sequence_name = :autogenerated

  validates :nombre, presence: true
  validates :identificacion, uniqueness: true, allow_nil: true
end
